# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2026 Dell Technologies

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: weekly}
    groups:
      kubernetes:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]
      charm:
        patterns: ["github.com/charmbracelet/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /operator
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /daemon
    schedule: {interval: weekly}
