# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright © 2026 Dell Technologies

{{- if .Values.installCRD }}
{{ .Files.Get "crd/principals.yaml" }}
---
{{ .Files.Get "crd/tenants.yaml" }}
{{- end }}