# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright © 2026 Dell Technologies

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kerberator.fullname" . }}
  labels:
    {{- include "kerberator.labels" . | nindent 4 }}